export { ReactComponent as ThinSearchIcon } from './search-thin.svg'
export { ReactComponent as BallIcon } from './ball.svg'
export { ReactComponent as ArrowLeftIcon } from './arrow-left.svg'
export { ReactComponent as CameraIcon } from './capture.svg'
export { ReactComponent as ShareIcon } from './share.svg'
